image: Ubuntu1804
configuration: Release
pull_requests:
  do_not_increment_build_number: true

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver

build_script:
- ps: dotnet pack src/Uploadcare.sln -c Release -o nuget_packages /p:Version="%GitVersion_NuGetVersion%"

after_build:
  - cmd: appveyor PushArtifact **/*.nupkg
