configuration: Release
pull_requests:
  do_not_increment_build_number: true

install:
  - choco install gitversion.portable -y

assembly_info:
  patch: false

before_build:
  - ps: gitversion /l console /output buildserver

build_script:
  - ps: dotnet pack src/Uploadcare.sln -c Release -o nuget_packages /p:Version=$env:GitVersion_NuGetVersion

after_build:
  - ps: Get-ChildItem ./*.nupkg -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
