name: main

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Pack NuGet Package
      run: dotnet pack src/Uploadcare.sln -c Release -o ./nuget_packages
