name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get GitVersion
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
    - name: Print Version
      run: cat ./version.txt
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Pack NuGet Package
      run: |
        cd src
        dotnet pack -c Release -o nuget_packages /p:Version=$(cat ./version.txt)
    - name: Push NuGet Package
      run: dotnet nuget push ./nuget_packages/*.nupkg -k ${{ secrets.NUGET_TOKEN }}
