name: release

on:
  push:
    tags:        
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Pack NuGet Package
      run: dotnet pack src/Uploadcare.sln -c Release -o ./nuget_packages /p:Version=($VERSION)
      env:
        VERSION: git rev-parse --abbrev-ref HEAD | grep -o '[.0-9]*'
    - name: Push NuGet Package
      run: dotnet nuget push src/Uploadcare/**/*.nupkg -n true -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
